const {chromium}=require('C:/Users/TANG/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});const p=await b.newPage({viewport:{width:375,height:812}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('file:///C:/Users/TANG/Desktop/MiniPro/ui/index.html');
assert.equal(await p.locator('#screen [data-action="coachslots"]').count(),2);
await p.locator('.quick [data-action="coach"]').click();assert.equal(await p.locator('#screen [data-action="coachslots"]').count(),3);
assert(await p.locator('#overlay').isHidden());
await p.locator('#coachSearch').fill('陈');assert.equal(await p.locator('#screen [data-action="coachslots"]').count(),1);
await p.locator('#coachSearch').fill('不存在');assert.equal(await p.locator('#screen [data-action="coachslots"]').count(),0);
await p.locator('[data-action="resetcoaches"]').click();
await p.locator('[data-action="coachtype"][data-value="私教课"]').click();assert.equal(await p.locator('#screen [data-action="coachslots"]').count(),2);
await p.locator('[data-action="coachtype"][data-value="全部"]').click();
await p.screenshot({path:'ui/preview/coaches.png'});
await p.locator('#screen [data-action="coachslots"][data-id="1"]').click();
assert.equal(await p.locator('#screen [data-action="book"]').count(),2);
await p.screenshot({path:'ui/preview/private-slots.png'});
await p.locator('[data-action="coachday"][data-id="24"]').click();assert.equal(await p.locator('#screen [data-action="book"]').count(),0);
await p.locator('[data-action="coachday"][data-id="18"]').click();await p.locator('#screen [data-action="book"][data-id="3"]').click();
assert((await p.locator('#sheetContent').innerText()).includes('陈教练'));
assert((await p.locator('#sheetContent').innerText()).includes('19:00'));
await p.locator('[data-action="confirmbook"]').click();await p.getByRole('heading',{name:'预约成功'}).waitFor();
await p.locator('#sheetContent [data-action="bookings"]').click();assert((await p.locator('#sheetContent').innerText()).includes('陈教练'));
await p.locator('[data-action="close"]').click();assert(await p.locator('#screen [data-action="book"][data-id="3"]').isDisabled());
await p.locator('[data-action="bookingmode"][data-value="course"]').click();assert(await p.locator('#screen [data-action="book"][data-id="3"]').isDisabled());
await p.locator('#tabbar button').first().click();await p.locator('#screen [data-action="coachslots"][data-id="1"]').click();assert(await p.locator('#screen [data-action="book"][data-id="3"]').isDisabled());
assert.equal(errors.length,0);console.log('PASS: coach list, teaching courses, published slots, empty day, correct coach/time, private card booking and duplicate prevention');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
